
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'wfxr/tmux-power'

set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'

set -g @tmux_power_theme 'gold'
set -g @tmux_power_show_user true
set -g @tmux_power_show_host true
set -g @tmux_power_show_session true
set -g @tmux_power_use_bold true
set -g @tmux_power_status_interval 1
set -g @tmux_power_time_format '%H:%M'
set -g @tmux_power_date_format '%F'

set -g @resurrect-dir '$HOME/.local/share/tmux/resurrect'
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.local/share/tmux/plugins/"
run-shell "$HOME/.local/share/tmux/plugins/tpm/tpm"

