# Simple status bar
set -g status-left-length 30
set -g status-right-length 80

set -g status-left "[#S] "
set -g status-right "#{?window_zoomed_flag,[ZOOM] ,}#{pane_current_command} | %Y-%m-%d %H:%M"

# Highlight current window clearly
setw -g window-status-current-format "#[bold][#I:#W]"
setw -g window-status-format " #I:#W "

# ===== Useful defaults =====

# Allow longer commands without weird wrapping behavior in some terminals
set -g default-terminal "tmux-256color"

# Better focus events for editors like nvim
set -g focus-events on

#GUI

# clearer status bar
set -g status-style "bg=colour235,fg=colour250"

# current window stands out
setw -g window-status-current-style "bg=colour148,fg=black,bold"
setw -g window-status-style "bg=default,fg=colour245"

# cleaner separators
setw -g window-status-separator " "

# make active pane border obvious
set -g pane-active-border-style "fg=colour148"
set -g pane-border-style "fg=colour238"

# show pane title on border
set -g pane-border-status top
set -g pane-border-format " #{pane_index} #{pane_current_command} "



## power

set -g @tmux_power_theme 'gold'
set -g @tmux_power_status_interval 1

set -g @tmux_power_left_a  '#{USER}@#h'
set -g @tmux_power_left_b  '#S'
set -g @tmux_power_left_c  ''
set -g @tmux_power_left_d  ''

set -g @tmux_power_right_w ''
set -g @tmux_power_right_x ''
set -g @tmux_power_right_y '%H:%M'
set -g @tmux_power_right_z '%F'
