
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind Space next-layout

# Reload config quickly
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# ===== Pane movement =====

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-H resize-pane -L 5
bind -n M-J resize-pane -D 5
bind -n M-K resize-pane -U 5
bind -n M-L resize-pane -R 5

# Resize panes with Shift + hjkl
bind -r H resize-pane -L 5
bind -r J resize-pane -D 3
bind -r K resize-pane -U 3
bind -r L resize-pane -R 5

# ===== Window movement =====

# Easier next/previous window
bind -r C-h previous-window
bind -r C-l next-window

# ===== Copy mode =====

# Enter copy mode with prefix + v
bind v copy-mode


## other binds
# bind-key g display-popup -w 80% -h 80% -E "lazygit"
bind-key g display-popup -d "#{pane_current_path}" -w 98% -h 98% -E "lazygit"

